### ISSUE TITLE
从中间删除时，格式化有问题

### ISSUE THREAD

**Issue by caprice** [santalu/mask-edittext#1]
bug: 定义手机格式"### #### ####",然后输入123 4567 8900，然后从头部开始删除比如2或者3后，格式变成了12  4567 8900，正确的应该是124  5678 900

**Comment by tinkooladik** [comment]
the same problem

**Comment by santalu** [comment]
Hi can you tell me what's the problem please? Thank you.

**Comment by tinkooladik** [comment]
@santalu [https://youtu.be/JzYwdf3cgKc](I've made a video)

**Comment by santalu** [comment]
Thank you for the video. I'll fix this asap.
