### ISSUE TITLE
Format gets duplicated when deleting

### ISSUE THREAD

**Issue by Namud** [santalu/mask-edittext#25]
Hello, Dear Developer.
Using the following code and format

<com.santalu.maskedittext.MaskEditText
        android:id="@+id/maskEditText"
        android:layout_width="match_parent"
        android:layout_height="50dp"
        android:layout_marginStart="21dp"
        android:layout_marginLeft="21dp"
        android:layout_marginTop="25dp"
        android:layout_marginEnd="21dp"
        android:layout_marginRight="21dp"
        android:background="@drawable/rounded_input_phone_pass"
        android:hint="Telephone nomery"
        android:inputType="phone"
        android:paddingLeft="23dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.0"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/imageView2"
        app:met_mask="+8(###) ### - ## - ##" />
After first  delete numbers  in mask. Happend this:
![01](https://user-images.githubusercontent.com/25370014/92099691-a2608f00-edfc-11ea-80a5-ae7fcd2a2a6b.jpg)
![02](https://user-images.githubusercontent.com/25370014/92099697-a5f41600-edfc-11ea-93b4-3d6421f2bcf9.jpg)

**Comment by santalu** [comment]
Hi, please upgrade to the latest version.

Checkout [README](./README.md) for more instructions

**Comment by Namud** [comment]
Thank you very  much!!!
