### ISSUE TITLE
Masking Fails when editing from between

### ISSUE THREAD

**Issue by rahulr4** [santalu/mask-edittext#5]
Hi,
I am using your mask edittext. It works fine in a normal user case but it fails when i edit a phone number from between
(568) 766-4444
Mask :- (###) ###-####

And then if i put the cursor in between, let say near the "-" and press backspace on the keyboard multiple times, so now the phone number becomes :- 
()))) )----85

**Comment by deyvidfk** [comment]
I have the same problem for a date mask for ## / ##.
When you delete the second character, the result is this:
Value: 25/08
In my case, it looks like this: /// 08.
Where did those other two bar characters come from?

**Comment by rahulr4** [comment]
Is this fixed ? Because this bug is closed

**Comment by santalu** [comment]
Yes, please update to 1.0.7 version. And feel free to reopen if anything happens

**Comment by rahulr4** [comment]
Ok one more thing. Just noticed that masking does not work with alphanumeric characters. It works only with numbers. 
For example i want to mask this text - "DFGH3TGH45HJY56" to "DFGH3-TGH45-HJY56".
This does not work. Please check that too.
Thanks.

**Comment by santalu** [comment]
It's also fixed with latest version
